# Generated by Django 5.2.1 on 2026-01-04 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='country_code',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
