# Generated by Django 5.2.1 on 2025-06-21 17:28

import store.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_usercart'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=store.models.category_image_path),
        ),
        migrations.AddField(
            model_name='category',
            name='image_alt',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=store.models.product_image_path),
        ),
        migrations.AddField(
            model_name='product',
            name='image_alt',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.DeleteModel(
            name='Image',
        ),
    ]
